version: '3.5'

services:
  milvus:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.3.9
    command: ["milvus", "run", "standalone"]
    ports:
      - "19530:19530"
      - "9091:9091"
    volumes:
      - milvus_data:/var/lib/milvus

volumes:
  milvus_data: